### ISSUE TITLE
Feature request: Add support for Module defaults

### ISSUE THREAD

**Issue by mamoep** [hitachi-vantara/vspone-block-ansible#37]
Please add a custom group in meta/runtime.yml to allow usage of module defaults for common parameters.
This would allow to write `connection_info` and other common parameters only once, making the playbooks more readable and avoid tedious repetition.

See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html

**Comment by rsahuHitachi** [comment]
We have handled it differently now,  You can check the **ansible_vault_vars** directory and variable files inside each subdirectory of the playbook dir

**Comment by mamoep** [comment]
That doesn't really address my point. I will still have to specify `connection_info: "{{ connection_info }}" ` and probably storage_system_info: "{{ storage_sys_info }}" in every task of my playbook.
Are you open for contributions?
