### ISSUE TITLE
Bug: Log folder causes issues while using collection

### ISSUE THREAD

**Issue by mamoep** [hitachi-vantara/vspone-block-ansible#38]
When installing the collection via Ansible Galaxy the log folder is not created, so using the module leads to permission error. 
`ansible-galaxy collection install hitachivantara.vspone_block`

`ansible-playbook storagesystem_facts.yml`

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: '/var/log/hitachivantara'`

This is problematic, as this is automatically done by Ansible Automation Hub/AWX when executing a playbook. I want to avoid a special execution environment just for this one collection. Please avoid logging per default or log to `/tmp`.

**Comment by rsahuHitachi** [comment]
This issue is fixed now, please use the latest version
